.PHONY: clean

clean:
	rm -f *.so *.ko *.o *.a */*.o */*.a
	rm -f *.d */*.d *.d.* */*.d.*
	rm -f *.sym *.tmp *.ver
	rm -f *.mod.c .*.cmd
	rm -f modules.order Module.symvers
	rm -rf .tmp_versions
	rm -f lcec_conf lcec_devices
	rm -f tests/*.bin
	rm -f *~ */*~
	rm -f #*# */#*#


